version: "3.7"
services:
    server:
        build:
            context: .
            dockerfile: Dockerfile-server
        environment:
            - PL_PWA_URL
            - PL_EMAIL_USER
            - PL_EMAIL_SERVER
            - PL_EMAIL_PORT
            - PL_EMAIL_PASSWORD
            - PL_EMAIL_FROM
            - PL_REPORT_ERRORS
            - PL_BILLING_ENABLED
            - PL_BILLING_STRIPE_SECRET
            - PL_MFA
        ports:
            - $PL_SERVER_PORT:3000
        volumes:
            - ./data:/data
            - ./docs:/docs
    pwa:
        build:
            context: .
            dockerfile: Dockerfile-pwa
        environment:
            - PL_SERVER_URL
            - PL_PWA_URL
            - PL_BILLING_ENABLED
            - PL_BILLING_DISABLE_PAYMENT
            - PL_BILLING_STRIPE_PUBLIC_KEY
        ports:
            - $PL_PWA_PORT:8000
        volumes:
            - ./pwa:/pwa
        command: ["build_and_start"]
